config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :users, only: [:show, :index] do
    member do
      patch 'avatar', to: 'users#avatar'
      get 'about', to: 'users#about'
    end
  end

  resources :pending_friendships, only: [:create, :destroy] do
    member do
      post 'accept'
    end
  end

  resources :friendships, only: [:destroy]
  resources :posts, only: [:show]
  resources :activities, only: [:index]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:index]
      resources :activities, only: [:index]
      resources :posts do
        member do
          put "like", to: "posts#upvote"
          put "dislike", to: "posts#downvote"
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :comments, only: [] do
        member do
          put "like", to: "comments#upvote"
          put "dislike", to: "comments#downvote"
        end
      end
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  default_scope { includes(:votes).order(created_at: :desc)}

  belongs_to :post
  belongs_to :user

  has_many :activities, as: :trackable, dependent: :destroy
  has_many :votes, as: :votable, class_name: "ActsAsVotable::Vote"

  validates :body, presence: true
  validates :post, presence: true
  validates :user, presence: true

  def up_votes
    get_likes.size
  end

  def down_votes
    get_dislikes.size
  end

  def total_votes
    (up_votes - down_votes)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApiController

  def create
    post = Post.find(params[:post_id])
    current_user = User.find(params[:current_user_id])
    comment = post.comments.new(comment_params)
    comment.user_id = current_user.id

    if comment.save
      track_activity(current_user, comment)
      render json: comment, current_user: current_user
    else
      render json: comment.errors
    end

  end

  def destroy
  end

  def upvote
    comment = Comment.find(params[:id])
    comment.liked_by current_user
    vote = ActsAsVotable::Vote.find_by(votable_id: comment.id, votable_type: "Comment")
    track_activity(vote)
    redirect_to :back
  end

  def downvote
    comment = Comment.find(params[:id])
    comment.disliked_by current_user
    vote = ActsAsVotable::Vote.find_by(votable_id: comment.id, votable_type: "Comment")
    track_activity(vote)
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% user = User.find(comment.user_id) %>

<div class="row">
    <div class="panel panel-inverse panel-comment">
      <div class="panel-body panel-body-inverse">
        <%= image_tag(user.avatar.comment_avatar) %>

        <div class="panel-comment-text">
            <p>
                <%= link_to user.username, user_path(user.username) %> <%= comment.body %>
            </p>
            <small>
                <%=link_to "<i class='fa fa-heart'></i>".html_safe, like_comment_path(comment), method: :put %>
                <%=link_to "<i class='fa fa-bomb'></i>".html_safe, dislike_comment_path(comment), method: :put %>
                <%= time_ago_in_words(comment.created_at) %> ago. | <%= comment.get_likes.size %> likes | <%= comment.get_dislikes.size %> bombs
            </small>
        </div>
      </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [post, Comment.new] do |f| %>
  <div class="row">
      <div class="panel panel-inverse panel-comment-form">
        <div class="panel-body panel-body-inverse">
          <div class="input-group">
            <span class="input-group-addon" id="sizing-addon1">
              <%= image_tag(user.avatar.comment_avatar) %>
            </span>
            <%= f.text_area :body, rows: 1, class: 'form-control', placeholder: 'Your Comment' %>
            <span class="input-group-addon">
              <%= f.submit "OK", class: 'btn btn-sm btn-primary pull-right' %>
            </span>
          </div>
        </div>
      </div>

  </div>
<% end %>