config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :users, only: [:show, :index] do
    member do
      patch 'avatar', to: 'users#avatar'
      get 'about', to: 'users#about'
    end
  end

  resources :pending_friendships, only: [:create, :destroy] do
    member do
      post 'accept'
    end
  end

  resources :friendships, only: [:destroy]
  resources :posts, only: [:show]
  resources :activities, only: [:index]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:index]
      resources :activities, only: [:index]
      resources :posts do
        member do
          put "like", to: "posts#upvote"
          put "dislike", to: "posts#downvote"
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :comments, only: [] do
        member do
          put "like", to: "comments#upvote"
          put "dislike", to: "comments#downvote"
        end
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  enum role: [:standard, :admin]

  devise :database_authenticatable, :registerable,
         :confirmable, :recoverable, :rememberable,
         :trackable, :validatable

  USERNAME_REGEX = /\A[a-zA-Z0-9\-_]+\z/i
  validates :username,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 20 },
    format: { with: USERNAME_REGEX }

  has_many :activities, dependent: :destroy
  has_many :pending_friendships, dependent: :destroy
  has_many :friendships, dependent: :destroy

  has_many :posts, through: :activities, source: :trackable, source_type: :Post, dependent: :destroy

  has_many :comments, dependent: :destroy

  # Avatar uploader using carrierwave
  mount_uploader :avatar, AvatarUploader
  after_commit :remove_previously_stored_avatar, on: :update

  def request_friendship(user_2)
    pending_friendships.create(friend: user_2)
  end

  def pending_friend_requests_from
    User.joins('INNER JOIN pending_friendships ON pending_friendships.user_id = users.id').where('pending_friendships.friend_id = ?', self.id)
  end

  def active_friends
    User.joins('INNER JOIN friendships ON friendships.friend_id = users.id').
         where('friendships.user_id = ?', self.id).
         union(User.joins(:friendships).
                    where('friendships.friend_id = ?', self.id)).
         includes(posts: [:votes, :comments])
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController

  # this is for searchbar
  def index
    @users = User.where(['username LIKE ? OR email LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%"]).limit(5)
    render json: @users, each_serializer: Api::V1::UserSerializer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @requests_from = current_user.pending_friend_requests_from
    @friends = current_user.active_friends

  end

  # Timeline
  def show
    @user = User.find_by(username: params[:id])
    @page = params[:page]
    @posts = @user.posts.includes(:votes, comments: [:votes])
    @friends = @user.active_friends # .includes(posts: [:votes, :comments])

  end

  # About
  def about
    @user = User.find_by(username: params[:id])
    @posts = Post.where(user_id: @user)
    @friends = @user.active_friends
  end

  # change to avatar
  def avatar
    @user = User.find(params[:id])
    @user.assign_attributes(params.fetch(:user, {}).permit(:avatar))
    authorize @user, :update?

    if params[:user].nil?
      flash[:error] = "You must chose a file."
    elsif @user.save
      flash[:notice] = "Profile Picture Updated"
    else
      flash[:error] = "Please choose a valid file to upload"
    end

    redirect_to user_path(@user.username)
  end


end

app/helpers/users_helper.rb
module UsersHelper

  def profile_friendship_button(user)
    # no button required for yourself
    return if current_user == user

    friendships = Friendship.where(user_id: [current_user, user], friend_id: [current_user, user])
    pending_friendships = PendingFriendship.where(user_id: [current_user, user], friend_id: [current_user, user])

    if friendships.empty? && pending_friendships.empty?
      link_to "Add Friend", pending_friendships_path(user_id: user), class: "btn btn-primary", method: :post
    elsif friendships.present?
      link_to "Remove Friend", friendship_path(friendships.take.id), class: "btn btn-primary", method: :delete
    elsif pending_friendships.take && pending_friendships.take.user == current_user
      link_to "Cancel Request", pending_friendship_path(pending_friendships.take.id), class: "btn btn-primary", method: :delete
    else
      content_tag(:div, class: "requested-friends-helper") do
        (link_to "<i class='fa fa-2x fa-check'></i>".html_safe, accept_pending_friendship_path(pending_friendships.take.id), method: :post) +
        (link_to "<i class='fa fa-2x fa-times'></i>".html_safe, pending_friendship_path(pending_friendships.take.id), method: :delete).html_safe
      end
    end

  end

end

app/views/users/_avatar_upload.html.erb
<%= form_for @user, url: avatar_user_path(@user), html: {multipart: true} do |f| %>
  <%= f.file_field :avatar %>
  <%= f.submit "Upload", class: "btn btn-primary margin-bottom-fix" %>
<% end %>

app/views/users/_friend_picture.html.erb
<div class="col-md-4">
  <div class="row text-center">
    <%= link_to user_path(user.username) do %>
      <%= image_tag(user.avatar.friendslist_avatar) %>
    <% end %>
  </div>
</div>

app/views/users/_friends.html.erb
<div class="row">
  <div class="panel">
    <div class="panel-heading">
      Friends (<%= @friends.count %>)
    </div>
    <div class="panel-body">
      <%= render partial: 'users/friend_picture', collection: @friends, as: :user %>
    </div>
  </div>
</div>

app/views/users/_header.html.erb
<% if policy(@user).update? %>
  <div class="modal fade" id='myModal' tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <!-- Modal -->
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title text-center" id="myModalLabel">Upload Avatar</h4>
        </div>
        <div class="modal-body">
          <%= render partial: 'avatar_upload' %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<div class="row">
  <div class="panel">
    <div class="panel-group">
      <div class="panel-body">
        <div class="avatar">
          <% if policy(@user).update? %>
            <i class="fa fa-2x fa-camera edit-avatar", data-target="#myModal", data-toggle="modal" ></i>
          <% end %>
          <%= image_tag(@user.avatar.profile_avatar) %>
        </div>
      </div>
      <div class="panel-footer">
        <%= profile_friendship_button(@user) %>
        <h3><%= @user.username.capitalize %></h3>

      </div>
    </div>


    <div class="panel-footer links" style="background: white;">
      <%= link_to "Timeline", user_path(@user.username), class: "btn btn-sm btn-default" %>
      <%= link_to "About", "#", class: "btn btn-sm btn-default" %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="col-xs-12 col-sm-6  col-md-3">
  <div class="thumbnail">
    <%= link_to user_path(user.username) do %>
      <%= image_tag(user.avatar.large_avatar) %>
      <div class="caption">
        <p class="text-center"><%= user.username %></p>
      </div>

    <% end %>
  </div>
  <div class="friendship-button text-center">
    <%= profile_friendship_button(user) %>
  </div>
</div>

app/views/users/_user_information.html.erb
<h3> user information partial</h3>

app/views/users/about.html.erb
<div id="user-profile-header">
  <%= render partial: 'header' %>

  <div class="container">
    <div class="row">
      <div class="col-md-offset-1 col-md-7">
        <% if policy(@user).owner? %>
          <h3>render edit button for information</h3>
        <% end %>
        <%= render partial: 'users/user_information' %>
      </div>
      <div class="col-md-3 friends">
        <%= render partial: 'users/friends' %>
      </div>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-head">
      <h3>Friend Requests From</h3>
    </div>
  </div>
  <div class="row requested-friends">
    <% @requests_from.each do |request| %>
      <%= react_component('UserIndex',
                                { user: request,
                                  avatar: request.avatar.large_avatar.to_s,
                                  friendship_button: profile_friendship_button(request).to_s
                                }) %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="panel panel-head">
      <h3>Friends</h3>
    </div>
  </div>
  <div class="row requested-friends">
    <% @friends.each do |friend| %>
      <%= react_component('UserIndex',
                                { user: friend,
                                  avatar: friend.avatar.large_avatar.to_s,
                                  friendship_button: profile_friendship_button(friend).to_s
                                }) %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div id="user-profile-header">
  <%= render partial: 'header' %>

  <div class="container">
    <div class="row">
      <div id="post-form" class="col-md-offset-1 col-md-7">
        <% if policy(@user).owner? %>
          <%= react_component('PostForm',
            { user: @user,
              authenticity_token: form_authenticity_token
            }) %>
        <% end %>
        <%= react_component("PostsContainer",
            {
              user: @user,
              current_user: current_user,
              form_token: form_authenticity_token,
              page: @page,
              post_path: api_v1_posts_path
            }) %>
      </div>
      <div class="col-md-3 friends">
        <%= render partial: 'users/friends' %>
      </div>
    </div>
  </div>

</div>