config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :users, only: [:show, :index] do
    member do
      patch 'avatar', to: 'users#avatar'
      get 'about', to: 'users#about'
    end
  end

  resources :pending_friendships, only: [:create, :destroy] do
    member do
      post 'accept'
    end
  end

  resources :friendships, only: [:destroy]
  resources :posts, only: [:show]
  resources :activities, only: [:index]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:index]
      resources :activities, only: [:index]
      resources :posts do
        member do
          put "like", to: "posts#upvote"
          put "dislike", to: "posts#downvote"
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :comments, only: [] do
        member do
          put "like", to: "comments#upvote"
          put "dislike", to: "comments#downvote"
        end
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  default_scope { includes(:votes).order(created_at: :desc)}

  belongs_to :user

  has_many :activities, as: :trackable, dependent: :destroy

  has_many :votes, as: :votable, class_name: "ActsAsVotable::Vote"

  has_many :comments, dependent: :destroy

  validates :body, presence: true
  validates :user, presence: true

  def up_votes
    get_likes.size
  end

  def down_votes
    get_dislikes.size
  end

  def total_votes
    (up_votes - down_votes)
  end

  def voted_for(current_user)
    self.votes.find_by(voter: current_user.id)
  end

end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApiController

  def index
    page = params[:page].present? ? params[:page] : 1
    # posts = Post.where(user_id: params[:user_id]).page(page).per(3)
    posts = Post.where(user_id: params[:user_id])
    # puts current_user
    render json: posts #, current_user: current_user
  end

  # def show
  #   # this is wrong (well kinda)
  #   posts = Post.where(id: params[:id])
  #   render json: posts, current_user: current_user
  # end

  def create
    post = Post.new(post_params)
    current_user = User.find(params[:current_user])
    post.user_id = current_user.id

    if post.save
      track_activity(current_user, post)
      render json: post # current_user: current_user
    else
      render json: post.errors
    end
  end

  def update
    post = Post.find(params[:id])
    post.assign_attributes(post_params)
    authorize post

    if post.save
      track_activity(post)
      flash[:notice] = "Post was updated"
    else
      flash[:error] = "There was an error updating the post. Please try again."
    end
    redirect_to :back
  end

  def destroy
    post = Post.find(params[:id])
    # authorize post

    if post.destroy
      render json: post
    else
      render json: post.errors
    end
  end

  def upvote
    post = Post.find(params[:post_id])
    current_user = User.find(params[:current_user_id])

    post.liked_by current_user
    vote = ActsAsVotable::Vote.find_by(votable_id: post.id, votable_type: "Post")
    track_activity(current_user, vote)
    render json: vote
  end

  def downvote
    post = Post.find(params[:post_id])
    current_user = User.find(params[:current_user_id])

    post.disliked_by current_user
    vote = ActsAsVotable::Vote.find_by(votable_id: post.id, votable_type: "Post")

    track_activity(current_user, vote)
    render json: vote
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def show
    @post = []
    post = Post.find(params[:id])
    @post.push(post)
    @user = User.find(post.user_id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit.html.erb
<!-- Modal -->
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title text-center" id="myModalLabel">Edit Post</h4>
    </div>
    <div class="modal-body">
      <%= form_for [post.user, post], class: "form-group" do |f| %>
        <%= f.text_area :body, rows: 4, class: 'form-control', value: post.body %>
        <div class="form-group">
          <%= submit_tag "Update", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/_edit_modal.html.erb
<!-- Modal -->
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title text-center" id="myModalLabel">Edit Post</h4>
    </div>
    <div class="modal-body">
      <%= form_for [post], class: "form-group" do |f| %>
        <%= f.text_area :body, rows: 4, class: 'form-control', value: post.body %>
        <div class="form-group">
          <%= submit_tag "Update", class: "btn btn-primary pull-right" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for [Post.new] do |f| %>
  <div class="row">
    <div class="col-md-offset-1">
      <div class="panel panel-inverse panel-post">
        <%= image_tag(user.avatar.post_avatar) %>
        <div class="panel-body panel-body-inverse">
          <%= f.text_area :body, rows: 4, class: 'form-control', placeholder: '' %>
        </div>
      </div>
      <div class="panel-footer panel-footer-inverse panel-footer-form">
        <%= f.submit "Post", class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="modal fade" id='<%= "myModal_#{post.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <%= render partial: 'posts/edit_modal', locals: {post: post} %>
</div>

<div class="row">
  <div class="col-md-offset-1">
    <div class="panel panel-inverse panel-post">
      <%= image_tag(user.avatar.post_avatar) %>


      <div class="panel-heading panel-heading-inverse">
        <%= link_to user.username, user_path(user.username) %> <%= link_to "posted this #{time_ago_in_words(post.created_at)} ago", "#" %>
        <div class="dropdown pull-right">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-2x fa-cog"></i></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Post", "#", "data-target": "#myModal_#{post.id}", "data-toggle": "modal" %></li>
            <li><%= link_to "Delete Post", post_path(post), method: :delete, class: 'navbar-link', data: {confirm: "Are you sure?"} %></li>
          </ul>
        </div>
      </div>

      <div class="panel-body panel-body-inverse panel-body-post">
        <div class="text-area">
          <%= post.body %>
        </div>
      </div>

    </div>

      <div class="panel-footer panel-footer-inverse panel-footer-post">
        <%= link_to "<i class='fa fa-2x fa-heart'></i>".html_safe, like_post_path(post), method: :put %>
        <%= post.get_likes.size - post.get_dislikes.size %>
        <%= link_to "<i class='fa fa-2x fa-bomb'></i>".html_safe, dislike_post_path(post), method: :put %>
      </div>
      <div class="panel-footer panel-footer-inverse panel-footer-votes">
        <% if post.get_likes.size != 0 %>
          <p>Your post has been Liked by <%= post.get_likes.size %> people</p>
        <% end %>

        <% if post.get_dislikes.size != 0 %>
          <p>Your post has been Bombed by <%= post.get_dislikes.size %> people</p>
        <% end %>
      </div>




      <div class="panel-group panel-group-comments">
        <div class="panel-heading panel-heading-inverse">
          <%= render partial: 'comments/form', locals: {post: post, user: current_user} %>
          <%# Some type of way to tell if it is on post show or another page %>
          <% if request.path.include?("/posts") %>
            <%= render partial: 'comments/comment', collection: post.comments %>
          <% elsif post.comments.first.present? %>
            <%= render partial: 'comments/comment', locals: {comment: post.comments.first} %>
            <% if post.comments.count > 1 %>
              <%= link_to "see more comments", post_path(post) %>
            <% end %>
          <% end %>

        </div>
      </div>



  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <%# = render partial: 'posts/post', locals: {post: @post, user: @user} %>

  <%= react_component("Posts",
    {
      posts: @post,
      current_user: @user,
      comment_authenticity_token: form_authenticity_token
    }) %>
</div>