config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :users, only: [:show, :index] do
    member do
      patch 'avatar', to: 'users#avatar'
      get 'about', to: 'users#about'
    end
  end

  resources :pending_friendships, only: [:create, :destroy] do
    member do
      post 'accept'
    end
  end

  resources :friendships, only: [:destroy]
  resources :posts, only: [:show]
  resources :activities, only: [:index]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:index]
      resources :activities, only: [:index]
      resources :posts do
        member do
          put "like", to: "posts#upvote"
          put "dislike", to: "posts#downvote"
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :comments, only: [] do
        member do
          put "like", to: "comments#upvote"
          put "dislike", to: "comments#downvote"
        end
      end
    end
  end

end

app/views/layouts/_flash.html.erb
<div class="flash">
  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button class="close" data-dismiss="alert" type="button">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button class="close" data-dismiss="alert" type="button">&times;</button>
    <%= flash[:error] %>
  </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button class="close" data-dismiss="alert" type="button">&times;</button>
    <%= flash[:alert] %>
  </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag("logo.png", height: "40", style: "margin-top: 7px;") %>
      <% end %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <div class="navbar-form navbar-left">
        <div class="form-group" id="the-basics">
            <input class="typeahead" type="text" placeholder="Search for User...">
        </div>
      </div>


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.username),class: 'navbar-link' do %>
              <%= image_tag(current_user.avatar.comment_avatar, size: "25") %><%= current_user.username.capitalize %>
            <% end %>
          </li>
          <li><%= link_to "Home", activities_path,class: 'navbar-link' %></li>
          <li><%= link_to "<i class='fa fa-user-plus'></i>".html_safe, users_path ,class: 'navbar-link' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog"></i></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path, class: 'navbar-link' %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-link' %></li>
              </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path, class: 'navbar-link' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bomba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

  <div class="container">
    <%= render partial: 'layouts/header'%>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>

  </div>

</body>
</html>